# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    upload_directory_projets: '%kernel.project_dir%/public/uploads/projets'
    upload_directory_taches: '%kernel.project_dir%/public/uploads/taches'
    images_directory: '%upload_directory_projets%'
    uploads_directory: '%upload_directory_taches%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Service/FileUploader.php'

    app.file_uploader_projets:
        class: App\Service\FileUploader
        arguments:
            $targetDirectory: '%upload_directory_projets%'

    app.file_uploader_taches:
        class: App\Service\FileUploader
        arguments:
            $targetDirectory: '%upload_directory_taches%'

    App\Controller\ProjetController:
        arguments:
            $projetImageUploader: '@app.file_uploader_projets'

    App\Controller\TacheController:
        arguments:
            $tachePieceUploader: '@app.file_uploader_taches'
